apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: my-pvc
spec:
  storageClassName: localdisk
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 100Mi
---
apiVersion: v1
kind: Pod
metadata:
  name: me-bb
spec:
  containers:
      - image: nginx
        name: nginx
        volumeMounts:
        - name: don-volume
          mountPath: /usr/share/nginx/html
  volumes:
  - name: don-volume
    persistentVolumeClaim:
     claimName: my-pvc
