apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: frais
  labels:
    app: mysql
    site: frais
  name: mysql
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
      site: frais
  template:
    metadata:
      namespace: frais
      labels:
        app: mysql
        site: frais
    spec:
      containers:
      - image: mysql:5.7
        name: mysql
        volumeMounts: 
        - mountPath: "/docker-entrypoint-initdb.d"
          name: localdisk
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom: 
           secretKeyRef:
            name: mysql-pass
            key: password
        - name: MYSQL_DATABASE
          value: "frais_db"      
      volumes: 
      - name: "localdisk"
        persistentVolumeClaim:
          claimName: app-claim
