apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: frais
  labels:
    app: nginx
    site: frais
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      site: frais
  template:
    metadata:
      namespace: frais
      labels:
        app: nginx
        site: frais
    spec:
      containers:
      - image: webdevops/php-nginx:5.6
        name: php-nginx
        volumeMounts: 
        - mountPath: "/app"
          name: localdisk
        - mountPath: /app/scripts
          name: config   
      volumes: 
      - name: "localdisk"
        persistentVolumeClaim:
          claimName: app-claim
      - name: "php-conn"
        configMap:
         name: php-conn
