apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: frais
  labels:
    app: nginx
    site: frais
  name: nginx
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
      site: frais
  template:
    metadata:
      namespace: frais
      labels:
        app: nginx
        site: frais
    spec:
      containers:
      - image: webdevops/php-nginx:5.6
        name: php-nginx
        resources: {}
