apiVersion: v1
kind: Service
metadata:
  namespace: frais
  name: nginx
spec:
  type: NodePort
  selector:
    app: nginx
    site: frais
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30007